/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * Access information about characters from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CharacterListResponse,
} from '../models/index';
import {
    CharacterListResponseFromJSON,
    CharacterListResponseToJSON,
} from '../models/index';

export interface GetCharactersRequest {
    page?: number;
    name?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get a list of characters
     */
    async getCharactersRaw(requestParameters: GetCharactersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharacterListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/character`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharacterListResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of characters
     */
    async getCharacters(requestParameters: GetCharactersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharacterListResponse> {
        const response = await this.getCharactersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
